versions = [ 
# renovate: datasource=docker depName=ghcr.io/anza-labs/library/kubernetes-sources
    "v1.34.3",
]

arch = [
    "amd64",
    "arm64",
    "riscv64",
]

targets = [
    "kube-apiserver",
    "kube-controller-manager",
    "kube-scheduler",
    "kube-proxy",
    "kubectl",
    "kubelet",
]