versions = [
# renovate: datasource=github-tags depName=chainguard-dev/kaniko
    "v1.25.5",
]

# renovate: datasource=docker
base_image = "ghcr.io/anza-labs/library/distroless/static:latest"

arch = [
    "amd64",
    "arm64",
]

targets = [
    "executor",
    "executor-debug",
    "warmer",
]
