versions = [
# renovate: datasource=github-tags depName=ziglang/zig
    "0.15.2",
]

# renovate: datasource=docker
base_image = "docker.io/library/alpine:3.23.3"

arch = [
    "amd64",
    "arm64",
    "ppc64le",
    "riscv64",
]
