versions = [
# renovate: datasource=repology depName=alpine_edge/chromium versioning=loose
    "144.0.7559.109-r0",
]

# renovate: datasource=docker
base_image = "docker.io/library/alpine:edge@sha256:115729ec5cb049ba6359c3ab005ac742012d92bbaa5b8bc1a878f1e8f62c0cb8"

arch = [
    "amd64",
    "arm64",
]
